# Generated by Django 4.2.5 on 2023-09-24 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_librarian'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='bookname',
            new_name='book_name',
        ),
    ]
